name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  go:
    name: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: actions/checkout@v3
      - run: go test -v ./...
